/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 03:43:33 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteTelicProtocolDecoder_ESTest extends EvosuiteTelicProtocolDecoder_ESTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
