/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Apr 09 03:43:33 GMT 2024
 */

package org.traccar.protocol;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;

@EvoSuiteClassExclude
public class EvosuiteTelicProtocolDecoder_ESTest_scaffolding {
  // Empty scaffolding for empty test suite
}
