/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 09 04:26:31 GMT 2024
 */

package org.traccar.protocol;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.SocketAddress;
import java.nio.ByteOrder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jboss.netty.buffer.ChannelBuffer;
import org.jboss.netty.buffer.DirectChannelBufferFactory;
import org.jboss.netty.buffer.DynamicChannelBuffer;
import org.jboss.netty.buffer.TruncatedChannelBuffer;
import org.jboss.netty.channel.Channel;
import org.jboss.netty.channel.DefaultChannelPipeline;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EvosuiteMeitrackProtocolDecoder_ESTest extends EvosuiteMeitrackProtocolDecoder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MeitrackProtocolDecoder meitrackProtocolDecoder0 = new MeitrackProtocolDecoder((MeitrackProtocol) null);
      try { 
        meitrackProtocolDecoder0.decode((Channel) null, (SocketAddress) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.traccar.protocol.MeitrackProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MeitrackProtocol meitrackProtocol0 = new MeitrackProtocol();
      MeitrackProtocolDecoder meitrackProtocolDecoder0 = new MeitrackProtocolDecoder(meitrackProtocol0);
      DynamicChannelBuffer dynamicChannelBuffer0 = new DynamicChannelBuffer(0);
      TruncatedChannelBuffer truncatedChannelBuffer0 = new TruncatedChannelBuffer(dynamicChannelBuffer0, 0);
      try { 
        meitrackProtocolDecoder0.decode((Channel) null, (SocketAddress) null, truncatedChannelBuffer0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Invalid index of 3, maximum is 0
         //
         verifyException("org.jboss.netty.buffer.TruncatedChannelBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MeitrackProtocol meitrackProtocol0 = new MeitrackProtocol();
      MeitrackProtocolDecoder meitrackProtocolDecoder0 = new MeitrackProtocolDecoder(meitrackProtocol0);
      DefaultChannelPipeline defaultChannelPipeline0 = new DefaultChannelPipeline();
      try { 
        meitrackProtocolDecoder0.decode((Channel) null, (SocketAddress) null, defaultChannelPipeline0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jboss.netty.channel.DefaultChannelPipeline cannot be cast to org.jboss.netty.buffer.ChannelBuffer
         //
         verifyException("org.traccar.protocol.MeitrackProtocolDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MeitrackProtocol meitrackProtocol0 = new MeitrackProtocol();
      MeitrackProtocolDecoder meitrackProtocolDecoder0 = new MeitrackProtocolDecoder(meitrackProtocol0);
      DirectChannelBufferFactory directChannelBufferFactory0 = new DirectChannelBufferFactory();
      ByteOrder byteOrder0 = ByteOrder.nativeOrder();
      ChannelBuffer channelBuffer0 = directChannelBufferFactory0.getBuffer(byteOrder0, 1491);
      TruncatedChannelBuffer truncatedChannelBuffer0 = new TruncatedChannelBuffer(channelBuffer0, 1491);
      Object object0 = meitrackProtocolDecoder0.decode((Channel) null, (SocketAddress) null, truncatedChannelBuffer0);
      assertNull(object0);
  }
}
